### ISSUE TITLE
Where's the code?

### ISSUE THREAD

**Issue by ccollicutt** [RIFTIO/RIFT.ware#2]
Hi,

The readme says "code coming soon". I'm curious as to when that will happen. It seems kind of unusual to have an open github repo with a readme that says the code will eventually be coming.

Thanks,
Curtis.

**Comment by JeremyMordkoff** [comment]
Hi Curtis,

There was a delay uploading the source for release 4.3. You can download 4.2 still. But since the doc, the binary packages and the code are now out of sync, we were recommending that people wait for the new code. Should be uploaded this week.

**Comment by JeremyMordkoff** [comment]
Posted. Sorry I forgot to close this.
